In [256]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
matplotlib.style.use('ggplot')

from __future__ import print_function
from six.moves import cPickle as pickle

from sklearn import preprocessing

data1 = pd.read_csv("AGW.csv")
data = np.genfromtxt("AGW.csv",delimiter=',')

In [257]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

In [258]:
print(data.shape)
print("\n ")
print(data[:,0])

(8743L, 30L)

 
[ nan  nan  nan ...,  nan  nan  nan]


In [259]:
data = np.delete(data,0,1)
data = np.delete(data,0,0)
print(data.shape)
print(data[:,:])

(8742L, 29L)
[[  1.26771000e+02   1.27636000e+02  -7.00000000e-01 ...,   1.27842000e+02
   -7.75000000e-01   0.00000000e+00]
 [  1.26470000e+02   1.27313000e+02  -8.25000000e-01 ...,   1.27612000e+02
   -7.45000000e-01   7.50000000e+01]
 [  1.26516000e+02   1.27132000e+02  -8.75000000e-01 ...,   1.27570000e+02
   -7.15000000e-01   5.44580000e+01]
 ..., 
 [  1.31839000e+02   1.31778000e+02   7.50000000e-02 ...,   1.31941000e+02
    9.50000000e-02   4.26230000e+01]
 [  1.31824000e+02   1.31779000e+02   1.00000000e-01 ...,   1.31954000e+02
    9.50000000e-02   4.26210000e+01]
 [  1.31873000e+02   1.31779000e+02   1.50000000e-01 ...,   1.31868000e+02
    9.50000000e-02   4.26190000e+01]]


In [260]:
print(data[:,-1])

[  0.     75.     54.458 ...,  42.623  42.621  42.619]


In [261]:
data = np.delete(data,-1,1)

In [262]:
print(data.shape)
print(data[:,:])


(8742L, 28L)
[[  1.26771000e+02   1.27636000e+02  -7.00000000e-01 ...,   1.27231000e+02
    1.27842000e+02  -7.75000000e-01]
 [  1.26470000e+02   1.27313000e+02  -8.25000000e-01 ...,   1.27043000e+02
    1.27612000e+02  -7.45000000e-01]
 [  1.26516000e+02   1.27132000e+02  -8.75000000e-01 ...,   1.26929000e+02
    1.27570000e+02  -7.15000000e-01]
 ..., 
 [  1.31839000e+02   1.31778000e+02   7.50000000e-02 ...,   1.31617000e+02
    1.31941000e+02   9.50000000e-02]
 [  1.31824000e+02   1.31779000e+02   1.00000000e-01 ...,   1.31614000e+02
    1.31954000e+02   9.50000000e-02]
 [  1.31873000e+02   1.31779000e+02   1.50000000e-01 ...,   1.31640000e+02
    1.31868000e+02   9.50000000e-02]]


In [263]:
fv = data[:,-1]

In [264]:
fv

array([-0.775, -0.745, -0.715, ...,  0.095,  0.095,  0.095])

In [265]:
n = pd.rolling_mean(data[:,2],5)
ma30 = pd.rolling_mean(data[:,2],30)

C:\Users\Jatin\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: pd.rolling_mean is deprecated for ndarrays and will be removed in a future version
  """Entry point for launching an IPython kernel.
C:\Users\Jatin\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: pd.rolling_mean is deprecated for ndarrays and will be removed in a future version
  


In [266]:
n[0:5] =data[0:5,2]
ma30[0:30] =data[0:30,2]

In [267]:
X = np.vstack((n,ma30,data[:,2]))

In [268]:
X.shape

(3L, 8742L)

In [269]:
X = np.transpose(X)
print(X.shape)
print(fv.shape)

(8742L, 3L)
(8742L,)


In [270]:
X.shape

(8742L, 3L)

In [271]:
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X, fv)

# Make predictions using the testing set
pred = regr.predict(X)
print('Coefficients: \n', regr.coef_)

Coefficients: 
 [ 0.35718665  0.17935501  0.45138591]


In [272]:
print("Mean squared error: %.6f"
      % mean_squared_error(fv, pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(fv, pred))

Mean squared error: 0.001531
Variance score: 0.96


In [273]:
pred[-20:]

array([ 0.0272737 ,  0.02876071,  0.04198075,  0.05505133,  0.07020677,
        0.07571403,  0.06800125,  0.08315669,  0.07187204,  0.05701553,
        0.06681317,  0.09325325,  0.09548757,  0.05969824,  0.08613832,
        0.06163363,  0.08286538,  0.06800887,  0.08286538,  0.10945493])

In [274]:
fv[-20:]

array([ 0.07 ,  0.08 ,  0.09 ,  0.09 ,  0.08 ,  0.075,  0.085,  0.09 ,
        0.085,  0.095,  0.09 ,  0.085,  0.075,  0.085,  0.095,  0.095,
        0.095,  0.095,  0.095,  0.095])

In [275]:
print('Coefficients: \n', regr.intercept_)
print('Coefficients: \n', regr.coef_)

Coefficients: 
 -0.00414268823478
Coefficients: 
 [ 0.35718665  0.17935501  0.45138591]


In [276]:
np.matmul(X,regr.coef_)

array([-0.6915493 , -0.81504024, -0.86443662, ...,  0.07215155,
        0.08700807,  0.11359762])